import type { Metadata } from "next";
import { Inter,  Open_Sans, Lato} from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";


const lato = Lato({
  subsets: ["latin"],
  weight: "400"
});
const inter = Inter({ subsets: ["latin"] });
const open_Sans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Zammane",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      {/* <head>
          <link rel="stylesheet" href="https://use.typekit.net/vsh8rwa.css"/>
        </head> */}
      <body className={lato.className}>
  
        
        <div className="font-normal">
        {children}
        </div>

    
        
        </body>
    </html>
  );
}


