import type { Metadata } from "next";
import { Inter,  Open_Sans } from "next/font/google";
import "./globals.css";
import Image from "next/image";

import Link from "next/link";



const inter = Inter({ subsets: ["latin"] });
const open_Sans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GreenShare",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      {/* <head>
          <link rel="stylesheet" href="https://use.typekit.net/vsh8rwa.css"/>
        </head> */}
      <body>
  
        
        {children}

    
        
        </body>
    </html>
  );
}


